# -*- coding: utf-8 -*-
"""powerproject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQ_oo2ek_LHd0etecAsCOg9IxbzL3rk5
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

# load sentiment analysis model
 sentiment = pipeline("sentiment-analysis")

 # smple product review (you can change only this text later)
 reviews="""the laptop starts quickly and works smoothly for daily tasks.
 The scrren quality is clear and good for wtching videos.
 Battery backup is average and needs charging often.
 The fan makes noise when many apps are running.
 Overall,it is a good laptop for student but not for gaming.
 """

import pandas as pd

sentences = reviews.split(",")

pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
        continue

    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        pros.append(s)

    elif result["label"] == "NEGATIVE":
        cons.append(s)

# Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

# Create table
df = pd.DataFrame({
    "Pros": pros,
    "Cons": cons
})

print(df)