# -*- coding: utf-8 -*-
"""sentence_transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjKpjvHiArbR-SWoU9W1rlrBMjUIUk3m
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util

# load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

# take input from user
text1 = input("Enter text1: ")
text2 = input("Enter text2: ")

# convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

# calculate similarity
similarity = util.cos_sim(embedding1, embedding2)
# convert tensor to float
score = float(similarity)

# show result
print("\nSimilarity score:", round(score, 2))

if score > 0.75:
    print("Similarity level: High")
elif score > 0.4:
    print("Similarity level: Medium")
else:
    print("Similarity level: Low")