# -*- coding: utf-8 -*-
"""TEXT GENERATION.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14E6n1lDvzFY3tdev6fHUhlpv2VhVSQvj
"""

!pip install transformers torch

from transformers import pipeline

 # Load text generation model(GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)

# Input prompt
prompt = "Artifical Intelligence in finance will"

#generate text
result = generator(prompt,max-length-50, num_return_sequences=1)

print("AI generator Text: ")
print(result[0]["generated_text"])