# -*- coding: utf-8 -*-
"""TIMETABLES GENARATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdNo0oyQyXl6KxrC4gN__2zK-teh69qv
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

# user inputs
subjects_input = input("Enter subjects (comma separated): ")
days_input = input("Enter days(comma separeted): ")
periods_per_day = int(input("Enter numbers of periods per day: "))

# process inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

# Validation
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
    print("Invalid input. Please try again.")
else:
  timetable ={}

  for days in days:
    timetable[days] = random.choices(subjects, k=periods_per_day)

    # create DataFrames
    df = pd.DataFrame(timetable)
    df.index = [f"period {i+1}" for i in range(periods_per_day)]

    print("\nTimetables generated successfully\n")
    display(df)

    # save timetable
    df.to_csv("timetables.csv")
    print("\nTimetable saved as timetable.csv")